const STORE_KEY = 'SEARCH';

export const FETCH_SEARCH_REQUEST = `${STORE_KEY}/FETCH_SEARCH_REQUEST`;
export const FETCH_SEARCH_SUCCESS = `${STORE_KEY}/FETCH_SEARCH_SUCCESS`;
export const FETCH_SEARCH_FAILURE = `${STORE_KEY}/FETCH_SEARCH_FAILURE`;
