const STORE_KEY = 'SEARCH';

export const FETCH_SEARCH_SUGGESTIONS_REQUEST = `${STORE_KEY}/FETCH_SEARCH_SUGGESTIONS_REQUEST`;
export const FETCH_SEARCH_SUGGESTIONS_SUCCESS = `${STORE_KEY}/FETCH_SEARCH_SUGGESTIONS_SUCCESS`;
export const FETCH_SEARCH_SUGGESTIONS_FAILURE = `${STORE_KEY}/FETCH_SEARCH_SUGGESTIONS_FAILURE`;

export const FETCH_SEARCH_RESULTS_REQUEST = `${STORE_KEY}/FETCH_SEARCH_RESULTS_REQUEST`;
export const FETCH_SEARCH_RESULTS_SUCCESS = `${STORE_KEY}/FETCH_SEARCH_RESULTS_SUCCESS`;
export const FETCH_SEARCH_RESULTS_FAILURE = `${STORE_KEY}/FETCH_SEARCH_RESULTS_FAILURE`;
export const REMOVE_SEARCH_RESULTS = `${STORE_KEY}/REMOVE_SEARCH_RESULTS`;
